{
 "title": "CPU",
 "panels": [
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_utilisation:avg1m{node=\"$node\"}",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "CPU Saturation (Load1)",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_saturation_load1:{node=\"$node\"}",
     "legendFormat": "Saturation"
    }
   ]
  }
 ]
}
{
 "title": "Memory",
 "panels": [
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_memory_utilisation:{node=\"$node\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Memory Saturation (Swap I/O)",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_memory_swap_io_bytes:sum_rate{node=\"$node\"}",
     "legendFormat": "Swap IO"
    }
   ]
  }
 ]
}
{
 "title": "Disk",
 "panels": [
  {
   "title": "Disk IO Utilisation",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_disk_utilisation:avg_irate{node=\"$node\"}",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Disk IO Saturation",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_disk_saturation:avg_irate{node=\"$node\"}",
     "legendFormat": "Saturation"
    }
   ]
  }
 ]
}
{
 "title": "Net",
 "panels": [
  {
   "title": "Net Utilisation (Transmitted)",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_net_utilisation:sum_irate{node=\"$node\"}",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Net Saturation (Dropped)",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_net_saturation:sum_irate{node=\"$node\"}",
     "legendFormat": "Saturation"
    }
   ]
  }
 ]
}
{
 "title": "Disk",
 "panels": [
  {
   "title": "Disk Utilisation",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - sum(max by (device, node) (node_filesystem_avail{fstype=~\"ext[24]\"})) / sum(max by (device, node) (node_filesystem_size{fstype=~\"ext[24]\"}))",
     "legendFormat": "Disk"
    }
   ]
  }
 ]
}